version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    restart: always