name: Build a docker image and push to docker hub repo
on:
  push:
    branches: ["main"]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image and push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with: 
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          context: .
          tags: test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io